- buildSrc/build.gradle
gradle-baseline-java classpath also updated to reflect the palantir bintray scheme.
While running `gradlew idea` there were unmet dependencies.
Heads up, the version of gradle-baseline-java was bumped to `0.12.0` .
> Add palantir bintray to build repos.

- common/server/framework/gradle.properties
- common/server/framework/src/main/java/org/curioswitch/common/server/framework/ServerModule.java
- common/server/framework/src/main/java/org/curioswitch/common/server/framework/config/ServerConfig.java
- common/server/framework/src/main/java/org/curioswitch/common/server/framework/redis/RedisModule.java
- common/server/framework/src/main/resources/curio-server-framework-nonlocal.conf
- common/server/framework/src/main/resources/reference.conf
- tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curioserver/tasks/DeployPodTask.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/StandardDependencies.java
> Enable graceful shutdown, support wildcard ingress paths, and don't validate

- tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curioserver/tasks/DeployPodTask.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/GcloudPlugin.java
Set netty available processors / GC threads based on deployment CPU and print flags on startup.
Also allow cloudbuild to push revision-id tags of docker images.
> Tweak JVM settings

- build.gradle
- common/server/framework/gradle.properties
- common/server/framework/src/main/java/org/curioswitch/common/server/framework/database/DatabaseModule.java
- settings.gradle
- tools/gradle-plugins/gradle-curiostack-plugin/build.gradle
- tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPlugin.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/StandardDependencies.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/tasks/CreateShellConfigTask.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/GcloudPlugin.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/ImmutableGcloudExtension.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/PlatformConfig.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/tasks/GcloudTask.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/tasks/SetupTask.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/util/PlatformHelper.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/grpcapi/GrpcApiPlugin.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/shared/CommandUtil.java
- Python is automatically setup
- All SDKs (gcloud, python, node, etc) are installed into home directory instead of project directory
- `rehash` task creates a shell script suitable for sourcing from a `.bashrc` to allow using downloaded tools. No need to install tools.
> Fix proto generation on windows and improve devenv setup.

- common/grpc/protobuf-jackson/gradle.properties
- common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/TypeSpecificMarshaller.java
Byte buddy 1.8.4 changed the default classload strategy to support JDK11, which loses `sun.misc.Unsafe` support. For now, explicitly enable the old strategy before making larger changes to support JDK11 with the non-unsafe loading strategy.
> Explicitly set byte-buddy class loading strategy to pre-JDK11 default.

- common/server/framework/gradle.properties
- common/server/framework/src/main/resources/application.conf
- gradle.properties
- tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curioserver/CurioServerPlugin.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curioserver/tasks/DeployPodTask.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/StandardDependencies.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/GcloudPlugin.java
- Docker image building / pushing done with `jib`
- `deploy` now sets JAVA_TOOL_OPTIONS instead of JAVA_OPTS so it is compatible with both gradle-docker-plugin and jib
- `patchAlpha` task added to patch an alpha deployment from Gradle
- continousTest / continuousCheck tasks removed since they're confusing, just use continuousBuild
- Cloudbuild tasks now all managed by gradle since no more docker daemon involvement
- Release build configuration
- gcloudLoginToCluster fixed to support both zone and regional clusters
- local servers `disableSslAuthorization` by default
> Publish curio 160

- gradle.properties
- tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/GcloudPlugin.java
- Curiostack doesn't override `PATH` completely anymore. Commands will use curiostack versions when the current directory is within a curiostack repository, and system ones elsewhere
- Adds armeria based pubsub library
- OpenJDK automatically downloaded (IntelliJ still needs manual setup)
- Update dependencies
- Gradle 5
- Armeria 0.75
> Fix configuration of gcloud tasks to work properly.

- common/web/base-web/src/state/store.ts
Might fix console error: `The previous state received by the reducer is of unexpected type. Expected argument to be an instance of Immutable.Collection or Immutable.Record with the following properties: [...]`
> Resetting state - Return globalInitialState which has language and route reducers.

- common/google-cloud/core/src/main/java/org/curioswitch/curiostack/gcloud/core/GcloudConfig.java
- common/google-cloud/core/src/main/java/org/curioswitch/curiostack/gcloud/core/GcloudModule.java
- common/google-cloud/core/src/main/resources/reference.conf
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/buildcache/CloudStorageBuildCacheServiceFactory.java
ServerModule already has a option to disable EDNS. Because I'd like to use same option for HTTP API client used by StorageModule, I added it to GcloudModule.
> Add a option to disable EDNS for google API client

- common/grpc/protobuf-jackson/build.gradle
- common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/DoParse.java
- common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/DoWrite.java
- common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/MessageMarshaller.java
- common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/ParseSupport.java
- common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/SerializeSupport.java
- common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/TypeSpecificMarshaller.java
- common/grpc/protobuf-jackson/src/test/java/org/curioswitch/common/protobuf/json/MessageMarshallerTest.java
- common/grpc/protobuf-jackson/src/test/proto/com/google/protobuf/util/json_test.proto
- printingEnumsAsInts
- sortingMapKeys
- unknown enum values are properly handled
- Unit test coverage is synced to completely match upstream
- Min java version raised to 8 given general deprecation of 7 across the ecosystem
> Add support for recent JsonFormat features.

- tools/build-images/java-cloud-builder/Dockerfile
bzip2 disappeared from the openjdk docker images we use as a base for building. It is a common enough utility and tiny enough to go ahead and install (libbz2 is already present this just adds the executable so especially small delta).
Fixes #318
> Install bzip2 in cloud builder.

- project.settings.gradle.kts
- tools/gradle-plugins/gradle-curiostack-plugin/build.gradle
- tools/gradle-plugins/gradle-curiostack-plugin/src/test/java/org/curioswitch/gradle/plugins/ci/CurioGenericCiPluginTest.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/test/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPluginToolsTest.java
- tools/gradle-plugins/gradle-curiostack-plugin/src/test/java/org/curioswitch/gradle/plugins/staticsite/StaticSitePluginTest.java
- tools/gradle-plugins/gradle-test-helpers/build.gradle.kts
- tools/gradle-plugins/gradle-test-helpers/src/main/java/org/curioswitch/gradle/testing/GradleTempDirectories.java
- tools/gradle-plugins/gradle-test-helpers/src/main/java/org/curioswitch/gradle/testing/ResourceProjects.java
- tools/gradle-plugins/gradle-test-helpers/src/main/java/org/curioswitch/gradle/testing/assertj/BuildResultAssert.java
- tools/gradle-plugins/gradle-test-helpers/src/main/java/org/curioswitch/gradle/testing/assertj/CurioGradleAssertions.java
- tools/gradle-plugins/gradle-test-helpers/src/main/java/org/curioswitch/gradle/testing/assertj/GradleRunnerAssert.java
- Temporary directories are created in the project's build directory instead of using junit to prevent interactions with TestKit
- Tests work correctly on Windows
- Added assertj assertions for running gradle tests
- Output printed if test fails, not if test succeeds
> Add gradle-test-helpers and clean up plugin tests.

- cluster/terraform/sysadmin/bootstrap/project.tf.yaml
- developer-portal/build.gradle.kts
Error message on CI when deploying seems to indicate the deploying project needs app engine enabled even if accessing a different one.
> Enable app engine API in main project.

- common/web/base-web/src/state/actions.ts
Sometimes we would like to pass `null` or `0` as a payload but they evaluate to false and do not get passed along.
> Explicitly check for undefined when evaluating the payload of an action.

- common/web/base-web/package.json
- common/web/base-web/src/dev/webpack/base.ts
- common/web/base-web/src/dev/webpack/prod.ts
- yarn.lock
Probably preferable to serve things like social images from a public gcloud bucket or something but it's harder to commit changes to the source. Maybe adding assets to a gcloud bucket with terraform is a better option. What do you think?
> Add support for static web assets

- common/web/base-web/src/state/actions.ts
I'm sorry for this oversight. The change merged before and released in 0.47 broke _a lot_ of things :crying_cat_face:
> Return only type when payload is undefined.

- cafe-map/client/web/package.json
- common/web/base-web/package.json
- common/web/base-web/src/state/reducers.ts
- eggworld/client/web/package.json
- package.json
- yarn.lock
Using empty string seemed to have been ok in previous versions of connected-react-router but not anymore.
> Fix URLs redirect to root.

- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/GcloudPlugin.java
> Only enable gcloud caching within project when gradle cache is enabled.

- common/web/base-web/src/hoc/injectReducer.tsx
- common/web/base-web/src/hoc/injectSaga.tsx
This reverts a change introduced in base-web 0.1.0 in order to prevent ordering issues.
> Use UNSAFE_componentWillMount when injecting sagas and reducers.

- eggworld/api/build.gradle
Just to prove this isn't required anymore after upgrading protobuf to 3.11.1.
> Enable eggworld API javadoc task.

- common/google-cloud/cloud-storage/src/main/java/org/curioswitch/curiostack/gcloud/storage/StorageClient.java
Successful delete are throwing exceptions without any content. I've confirmed inside the bucket that the files have indeed been deleted.
I can't find actual documentation in the REST API docs, but the official XML docs and various code samples online state that 204/NO_CONTENT is returned when a successful delete happens.
https://cloud.google.com/storage/docs/xml-api/delete-object
> Use correct HttpStatus for successful cloud storage file deletion.

- build.gradle
Gradle correctly finds our Java 8 modules our depending on a Java 11 module in the test classpath. Test should be allowed to be Java 11 regardless of the target for the sources.
> Override JVM version for test classpaths to support gradle metadata.

- common/server/framework/src/main/java/org/curioswitch/common/server/framework/armeria/ClientBuilderFactory.java
When starting a service that builds a grpc client to connect to another service, an error is thrown
```
Exception in thread "main" java.lang.IllegalArgumentException: Not a valid domain name: 'gproto+https://developer-gateway.mydomain.com:8080/api/'
```
Looking at https://github.com/line/armeria/blob/master/core/src/main/java/com/linecorp/armeria/client/Endpoint.java#L81 it looks like the authority should be passed in instead of the full URI.
I tried to test the change in this repo using the Instagram scraper but I didn't have the necessary configs set up (db, API keys).
> Use URI authority when parsing endpoint.

- common/grpc/protobuf-jackson/src/main/java/org/curioswitch/common/protobuf/json/ProtoFieldInfo.java
Armeria uses curiostack/protobuf-jackson as DefaultJsonMarshaller to support gjson or gjson-web format. When using proto version 2 with required field in Armeria, try to support gjson or gjson-web, an error occurred when initializing FramedGrpcService and cannot be executed. if protobuf-jackson call `buildPartial` instead of `build`, can be support proto version 2 required field
https://github.com/line/armeria/issues/3273
> support proto version 2 for armeria

- tools/curiostack-bom/build.gradle.kts
Before the curiostack 0.6.0 update `org.eclipse.jgit` was upgraded [from 5.7 to 5.8](https://github.com/curioswitch/curiostack/commit/fa5eab68884c124d983ed7d4903668ff33d73eae#diff-9b64b25492de5007587b7ef5daf56eda77d8c6dffe77d2e44609364cf7b5d6aaR275). While reading the [changelog for 5.8](https://wiki.eclipse.org/JGit/New_and_Noteworthy/5.8), it mentioned that it split the ssh (and some other) dependencies to separate bundles.
In our project we use `org.ajoberstar.git-publish` which depends on jgit and I believe the upgraded version in the curio bom is preventing the tool from working properly similar to what is mentioned in the eclipse bug tracker: https://bugs.eclipse.org/bugs/show_bug.cgi?id=566260.
```
Step #1: Caused by: org.eclipse.jgit.api.errors.TransportException: …
```
> Add jgit.ssh.jsch bundle dep to the bom

- settings.gradle.kts
- tools/curiostack-bom/build.gradle.kts
- tools/gradle-plugins/gradle-curiostack-plugin/build.gradle.kts
- tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curioserver/CurioServerPlugin.java
- tools/gradle-plugins/gradle-golang-plugin/build.gradle.kts
- tools/gradle-plugins/gradle-golang-plugin/src/main/java/org/curioswitch/gradle/golang/tasks/JibTask.java
- yarn.lock
For curiostack v0.7.1, `jackson v2.12.1` is not compatible with `jib-gradle-plugin v2.1.0` so the jib task fails. This is an attempt to upgrade jib to the latest v2.8.0.
Two things:
1. I needed to include the `jib-build-plan` dependency for `jib-core` in the modules because it is not being imported transitively, so even if I change the jib dependency configuration to "api", it does not work (https://github.com/GoogleContainerTools/jib/blob/5c5cf90c6d82ea7b7f21a7c1513da1ee8d7b9a54/build.gradle#L374). Do you think this is intentional or should we open an issue?
2. This test is failling but you might have a quicker fix than if I tried to solve it
```
GolangPluginTest > CanSetEnvironmentVariable > setEnvironmentVariable() STANDARD_ERROR
SLF4J: Class path contains multiple SLF4J bindings. …
```
> Upgrade jib-gradle-plugin to v2.8.0
