tools/gradle-plugins/gradle-curiostack-plugin/README.md, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/ImmutableGcloudExtension.java
Not sure if you wanted this change in curiostack as well.
=> Update the default gcloud version

build.gradle, settings.gradle, tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/ci/CurioGenericCiPlugin.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPlugin.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/tasks/SetupGitHooks.java
Also allows diffing against upstream remote and more flexibility of continuous build types.
=> Add a task to setup prepush hook which runs affected tests.

common/server/framework/gradle.properties, common/server/framework/src/main/java/org/curioswitch/common/server/framework/database/DatabaseUtil.java, common/server/framework/src/main/java/org/curioswitch/common/server/framework/redis/ProtobufRedisLoadingCache.java, common/server/framework/src/main/java/org/curioswitch/common/server/framework/redis/RedisModule.java, tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/StandardDependencies.java
Also make SFMMapper a singleton for stability with tests.
=> Use cluster client for redis.

build.gradle, settings.gradle, tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPlugin.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/tasks/CreateShellConfigTask.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/ImmutableGcloudExtension.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/grpcapi/GrpcApiPlugin.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/shared/CommandUtil.java
=> Use miniconda for environment setup.

build.gradle, common/server/framework/build.gradle, common/server/framework/gradle.properties, common/server/framework/src/main/java/org/curioswitch/common/server/framework/staticsite/StaticSiteService.java, settings.gradle, tools/gradle-plugins/gradle-curiostack-plugin/build.gradle, tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPlugin.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/StandardDependencies.java
=>  Update dependencies and allow serving index.html from non-root paths … 

README.md
taking descriptions from @chokoswitch's email.
=> Add instruction to run :setup for the first time

common/web/base-web/src/dev/scripts/test.ts
The main usage being `yarn test -u`
=> Propagate command line parameters to the main jest command.

build.gradle, common/google-cloud/cloud-storage/gradle.properties, common/google-cloud/cloud-storage/src/main/java/org/curioswitch/curiostack/gcloud/storage/FileWriter.java, common/google-cloud/cloud-storage/src/main/java/org/curioswitch/curiostack/gcloud/storage/MetricLabels.java, common/google-cloud/cloud-storage/src/main/java/org/curioswitch/curiostack/gcloud/storage/StorageClient.java, common/google-cloud/cloud-storage/src/main/java/org/curioswitch/curiostack/gcloud/storage/StorageModule.java, common/google-cloud/core/build.gradle, common/google-cloud/core/gradle.properties, common/google-cloud/core/src/main/java/org/curioswitch/curiostack/gcloud/core/GcloudModule.java, common/google-cloud/iam/gradle.properties, common/google-cloud/trace/gradle.properties, common/server/framework/gradle.properties, settings.gradle, tools/gradle-plugins/gradle-curiostack-plugin/build.gradle, tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/StandardDependencies.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/buildcache/CloudStorageBuildCacheServiceFactory.java
- Add some more APIs to storage library for use in non-server situations
- Add metrics to storage operations
- Update dependencies
=> Curiostack 139

gradle.properties, tools/gradle-plugins/gradle-curiostack-plugin/gradle.properties, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curioserver/CurioServerPlugin.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curioserver/ImmutableDeploymentExtension.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curioserver/tasks/DeployPodTask.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/gcloud/tasks/KubectlTask.java
Use jib for building / pushing images and configure release building.
=> Curio 160 RC

tools/cloudbuild-github-functions/package.json, tools/cloudbuild-github/package.json, tools/cloudbuild-github/src/cli/cloudbuild-cli-deploy.ts, tools/cloudbuild-github/src/notifier.ts
- Updates dependencies
- Quite a large version upgrade in googleapis / auth, hopefully makes the auth token fetch which we are seeing failures with more robust
- Updates runtime to nodejs10
- Maybe more efficient
- Breaks windows support temporarily
=> Fix memory flag and GitHub notifier.

tools/build-images/java-cloud-builder/Dockerfile
=> Install ca-certificates to cloud builder.

cloudbuild-release.yaml, cloudbuild.yaml, tools/cloudbuild-github-functions/config.yml
Release build is very old and none of the builds are properly caching miniconda / gcloud
=> Fix cloudbuild.

tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPlugin.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/curiostack/tasks/UpdateGradleWrapperTask.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/resources/curiostack/get-jdk.sh, tools/gradle-plugins/gradle-curiostack-plugin/src/test/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPluginTest.java, tools/gradle-plugins/gradle-curiostack-plugin/src/test/resources/test-projects/gradle-curiostack-plugin/kitchen-sink/build.gradle.kts, tools/gradle-plugins/gradle-curiostack-plugin/src/test/resources/test-projects/gradle-curiostack-plugin/kitchen-sink/settings.gradle.kts
=> Have CuriostackPlugin add get-jdk.sh to wrapper as needed.

tools/gradle-plugins/gradle-golang-plugin/build.gradle.kts, tools/gradle-plugins/gradle-golang-plugin/gradle.properties, tools/gradle-plugins/gradle-golang-plugin/src/main/java/org/curioswitch/gradle/golang/tasks/JibTask.java
=> Use current gradle-jib-plugin version and update to latest API.

tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/codelabs/tasks/ExportDocsTask.java
Might make it easier to upgrade versions.
=> Deprecated instead of remove unnecessary urlPrefix property.

common/server/framework/src/main/java/org/curioswitch/common/server/framework/redis/ProtobufRedisLoadingCache.java, common/server/framework/src/test/java/org/curioswitch/common/server/framework/redis/ProtobufRedisLoadingCacheTest.java
=> Return whether the key was deleted or not in ProtobufRedisLoadingCache.

tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/terraform/TerraformSetupExtension.java, tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/terraform/TerraformSetupPlugin.java, tools/gradle-plugins/gradle-curiostack-plugin/src/test/java/org/curioswitch/gradle/plugins/terraform/TerraformSetupPluginTest.java
=> Allow configuring terraform plugins.

tools/gradle-plugins/gradle-curiostack-plugin/src/main/java/org/curioswitch/gradle/plugins/terraform/tasks/ConvertConfigsToJsonTask.java, tools/gradle-plugins/gradle-curiostack-plugin/src/test/java/org/curioswitch/gradle/plugins/curiostack/CuriostackPluginTest.java, tools/gradle-plugins/gradle-curiostack-plugin/src/test/resources/test-projects/gradle-curiostack-plugin/kitchen-sink/terraform/dummy2.tf
=> Fix resolution of output path for .tf files.

common/google-cloud/cloud-storage/src/main/java/org/curioswitch/curiostack/gcloud/storage/StorageClient.java
Turned out to be a red herring :yum:
=> Fix CloudStorage delete RuntimeException message.

common/web/base-web/index.d.ts
We use mp4s for micro-interactions/animations in our projects so it would be helpful to have this type 😄
=> Add mp4 to types.

cloudbuild-release.yaml, cloudbuild.yaml
=> Download cache to temp file for master / release build like PR build.

build.gradle.kts, common/testing/assertj-protobuf/gradle.properties, settings.gradle.kts, tools/curiostack-bom/build.gradle.kts
=> Add nexus publishing plugin.
